#!/bin/bash
# OAuth /oauth/token load test — generated by Codebuff
# Run: bash apps/web/oauth_load_test.sh
set -e

BASE="http://localhost:8080"
echo "=== OAuth /oauth/token Memory Leak Load Test ==="
echo ""

BASELINE_MEM=$(docker stats backend-go-backend-1 --no-stream --format "{{.MemUsage}}" 2>/dev/null)
echo "Baseline memory: $BASELINE_MEM"

# Burst test
echo "--- Burst: 200 conncurrent POST /oauth/token ---"
ab -n 200 -c 20 -T "application/x-www-form-urlencoded" "$BASE/oauth/token" 2>&1 | tail -5

# Sustained load
echo "--- Sustained: 54 requests over 3 min ---"
END=$((SECONDS + 180))
REQ_COUNT=0
RATE_LIMITED=0
while [ $SECONDS -lt $END ]; do
  for i in 1 2 3; do
    HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$BASE/oauth/token" \
      -d "grant_type=authorization_code&code=load_test_$(date +%s%N)&client_id=load_test_client" \
      -H "Content-Type: application/x-www-form-urlencoded" 2>/dev/null)
    REQ_COUNT=$((REQ_COUNT + 1))
    [ "$HTTP_CODE" = "429" ] && RATE_LIMITED=$((RATE_LIMITED + 1))
    sleep 3.1
  done
  docker stats backend-go-backend-1 --no-stream --format "  MEM: {{.MemUsage}}" 2>/dev/null
done

echo "Requests: $REQ_COUNT | Rate-limited: $RATE_LIMITED"
curl -s 'http://localhost:8080/debug/pprof/heap?gc=1' > /dev/null
POST_MEM=$(docker stats backend-go-backend-1 --no-stream --format "{{.MemUsage}}" 2>/dev/null)
echo "Post-test memory (after GC): $POST_MEM"
echo "=== Done ==="
echo "Compare: baseline=$BASELINE_MEM vs post=$POST_MEM"
