#!/usr/bin/env bash
# =============================================================================
# Gomo6 — Generate all required keys for .env
# =============================================================================
# Usage:
#   ./scripts/generate-keys.sh              # generate and write to .env
#   ./scripts/generate-keys.sh --dry-run    # print without writing
#   ./scripts/generate-keys.sh --help       # show help
#
# Existing keys in .env are preserved (regenerated only if missing).
# To force regeneration of ALL keys: ./scripts/generate-keys.sh --force
# =============================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# ── Args ────────────────────────────────────────────────────────────────────
DRY_RUN=false
FORCE=false
ENV_FILE=".env"

for arg in "$@"; do
    case "$arg" in
        --dry-run)  DRY_RUN=true ;;
        --force)    FORCE=true ;;
        --help|-h)
            echo "Usage: $0 [--dry-run] [--force] [.env-file]"
            echo ""
            echo "Options:"
            echo "  --dry-run   Print keys without writing to file"
            echo "  --force     Regenerate ALL keys (overwrite existing)"
            echo "  .env-file   Target file (default: .env)"
            exit 0
            ;;
        --*)        echo "Unknown option: $arg"; exit 1 ;;
        *)          ENV_FILE="$arg" ;;
    esac
done

# ── Helpers ─────────────────────────────────────────────────────────────────
gen_hex() {
    local bytes=$1
    openssl rand -hex "$bytes" 2>/dev/null
}

gen_random_string() {
    local len=$1
    openssl rand -base64 "$len" 2>/dev/null | tr -d '=/+' | head -c "$len"
}

# ── Check existing .env ─────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "$FORCE" = false ]; then
    echo -e "${YELLOW}⚠  $ENV_FILE already exists. Existing keys will be preserved.${NC}"
    echo -e "${YELLOW}   Use --force to regenerate all keys.${NC}"
    echo ""
fi

# ── Generate keys ───────────────────────────────────────────────────────────
echo -e "${CYAN}🔑 Generating secure keys...${NC}"
echo ""

# JWT_SECRET — 32 bytes (64 hex chars)
JWT_SECRET=$(gen_hex 32)
echo -e "  ${GREEN}✓${NC} JWT_SECRET              (64 hex chars)"

# FEDERATION_KEY — 16 bytes (32 hex chars)
FEDERATION_KEY=$(gen_hex 16)
echo -e "  ${GREEN}✓${NC} FEDERATION_KEY          (32 hex chars)"

# MESSENGER_ENCRYPTION_KEY — 32 bytes (64 hex chars)
MESSENGER_ENCRYPTION_KEY=$(gen_hex 32)
echo -e "  ${GREEN}✓${NC} MESSENGER_ENCRYPTION_KEY (64 hex chars)"

# REDIS_PASSWORD — 16 bytes (32 hex chars)
REDIS_PASSWORD=$(gen_hex 16)
echo -e "  ${GREEN}✓${NC} REDIS_PASSWORD          (32 hex chars)"

echo ""

# ── Build .env content ──────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "$FORCE" = false ]; then
    # Merge: keep existing values, add missing ones
    echo -e "${CYAN}📝 Merging with existing $ENV_FILE...${NC}"

    CONTENT=$(cat "$ENV_FILE")

    add_if_missing() {
        local key=$1
        local value=$2
        if ! echo "$CONTENT" | grep -q "^${key}="; then
            CONTENT="${CONTENT}
${key}=${value}"
            echo -e "  ${GREEN}+${NC} Added ${key}"
        else
            echo -e "  ${YELLOW}=${NC} Kept existing ${key}"
        fi
    }

    add_if_missing "JWT_SECRET" "$JWT_SECRET"
    add_if_missing "FEDERATION_KEY" "$FEDERATION_KEY"
    add_if_missing "MESSENGER_ENCRYPTION_KEY" "$MESSENGER_ENCRYPTION_KEY"
    add_if_missing "REDIS_PASSWORD" "$REDIS_PASSWORD"
    add_if_missing "DOMAIN" "localhost"
    add_if_missing "ENVIRONMENT" "production"

else
    # Fresh .env
    CONTENT="# =============================================================================
# Gomo6 — Environment Configuration
# Generated by scripts/generate-keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# =============================================================================
# DO NOT commit this file to git. It contains production secrets.
# =============================================================================

# ── Domain ──────────────────────────────────────────────────────────────────
DOMAIN=localhost

# ── Security ────────────────────────────────────────────────────────────────
# JWT signing secret (HS256, 32 bytes)
JWT_SECRET=${JWT_SECRET}

# Federation key for ActivityPub interop (16 bytes)
FEDERATION_KEY=${FEDERATION_KEY}

# ── Environment ─────────────────────────────────────────────────────────────
ENVIRONMENT=production

# ── Messenger Encryption ────────────────────────────────────────────────────
# AES-256-GCM key for message encryption at rest (32 bytes)
# Backend will NOT start without this key
MESSENGER_ENCRYPTION_KEY=${MESSENGER_ENCRYPTION_KEY}

# ── Redis ───────────────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
"
fi

# ── Output ──────────────────────────────────────────────────────────────────
if [ "$DRY_RUN" = true ]; then
    echo -e "${CYAN}DRY RUN — would write to $ENV_FILE:${NC}"
    echo ""
    echo "$CONTENT"
else
    echo "$CONTENT" > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo -e "${GREEN}✅ Keys written to $ENV_FILE (mode 600)${NC}"
fi

echo ""
echo -e "${CYAN}📋 Summary:${NC}"
echo -e "  JWT_SECRET                = ${JWT_SECRET:0:8}...${JWT_SECRET: -8}"
echo -e "  FEDERATION_KEY            = ${FEDERATION_KEY:0:8}...${FEDERATION_KEY: -8}"
echo -e "  MESSENGER_ENCRYPTION_KEY  = ${MESSENGER_ENCRYPTION_KEY:0:8}...${MESSENGER_ENCRYPTION_KEY: -8}"
echo -e "  REDIS_PASSWORD            = ${REDIS_PASSWORD:0:8}...${REDIS_PASSWORD: -8}"
echo ""
echo -e "${YELLOW}⚠  IMPORTANT: Back up these keys. Losing MESSENGER_ENCRYPTION_KEY${NC}"
echo -e "${YELLOW}   means ALL encrypted messages become unrecoverable.${NC}"
echo ""
